### ISSUE TITLE
Convert graph to use new Jenkins icons

### ISSUE THREAD

**Issue by timja** [jenkinsci/pipeline-graph-view-plugin#11]
Currently we're using the blue ocean icons, we should try use the new Jenkins ones

![image](https://user-images.githubusercontent.com/21194782/119990653-7d323300-bfc0-11eb-82e4-5d679ca428e5.png)

![image](https://user-images.githubusercontent.com/21194782/119990678-86bb9b00-bfc0-11eb-8c34-6e94a0ce60a5.png)

**Comment by mPokornyETM** [comment]
Nice idea, but which icons you want use? Because listed icons are about build and job. Here are stages. I am not sure, if there is way to check, that the stage runs first time.

**Comment by kaltepeter** [comment]
@timja @mPokornyETM I am interested in picking this one up. I think I have a rough idea of where to find the icons and colors. 

To clarify similar to the previous question, are the symbols the ones found here: https://github.com/jenkinsci/jenkins/tree/master/war/src/main/resources/images/symbols and the colors found here: https://weekly.ci.jenkins.io/design-library/Colors/?

**Comment by mPokornyETM** [comment]
@kaltepeter you are welcome
1. I am not sure, I thing @timja  want just change icons, this hat nothing to do with colors.
2. In the /symbols directory does not exists icons like success, failed ... . Or I am blind ;-)

I thing it will be best to wait for timja´s answer

**Comment by timja** [comment]
The icons are an SVG sprite in here:
https://github.com/jenkinsci/jenkins/blob/master/war/src/main/webapp/images/build-status/build-status-sprite.svg

> Nice idea, but which icons you want use? Because listed icons are about build and job. Here are stages. I am not sure, if there is way to check, that the stage runs first time.

I would like to use the same icons so the graph / log status icons are the same as the build icons.

**Comment by kaltepeter** [comment]
Sounds good @timja I should be able to take a look at this tonight or so.

**Comment by timja** [comment]
Reverted in https://github.com/jenkinsci/pipeline-graph-view-plugin/pull/174

due to https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/173
