### ISSUE TITLE
show stage basic information

### ISSUE THREAD

**Issue by mPokornyETM** [jenkinsci/pipeline-graph-view-plugin#146]
### What feature do you want to see added?

When user click in pipeline-graph on stage, he will be navigated to pipeline-steps. So far so good, but the user see the message *Select a node to view console output.*

![image](https://user-images.githubusercontent.com/89339813/193461356-79d83cce-d779-45d6-8dcf-96666816d537.png)

This might be true, because you has not selected any steps. But it will be fine, when are here some stage information, like

**Stage 'Install WinCC OA'**
Started 18 min ago
Took 9 min 31 sec
Status : (Success / Failed / Unstable ..)
Link to last one step (in my case I have ~ 100 steps)

optional (nice to have):
On node env.NODE_NAME
count of steps ?
exception - link to step (the last one) which produce a exception (why is the stage not GREEN)

**Comment by timja** [comment]
Another option would be to move the steps into the log area and expand them by clicking on them.

any thoughts @timbrown5 ?

**Comment by timbrown5** [comment]
> Another option would be to move the steps into the log area and expand them by clicking on them.
> 
> any thoughts @timbrown5 ?

I think it's worth considering - makes it more akin to the BlueOcean Pipeline (which seems to be a popular request).

We could move to a more cardified style as well (like you have done with the console view):

![Screenshot 2022-10-03 at 10 11 44](https://user-images.githubusercontent.com/4447764/193544747-baf67225-509e-4c3b-b994-f03016eaf1f1.png)

**Comment by mPokornyETM** [comment]
that means?

stages | steps | console-output

And what the 'Details' means ? Details for selected stage or details for whole job?
When it is per stage, I like it. May be is the field too big. And It will be fine full stage name there. In case somebody want truncates the stage name in first column (or just make the column to small)

How it looks with parallel stages and nested stages?
Thx

**Comment by timbrown5** [comment]
> And what the 'Details' means ? Details for selected stage or details for whole job?

That is the stage details, (w.g. the details of 'Build' in this case).

@timja, just splitballing, but how easy would it be to allow cards to be rearranges by the user? Just wondering if the user could drag cards around (and maybe resize) to get the layout they prefer.
I was also thinking the console output could be made into a card (as it looks like a card, but isn't one). Hopefully, this would allow for it to be more portable - e.g. to the Graph view.

**Comment by timja** [comment]
>  just splitballing, but how easy would it be to allow cards to be rearranged by the user (e.g. drag and drop)? Just wondering if the user could drag cards around (and maybe resize) to get the layout they prefer.

not terribly hard, just need to figure out how / where to store it, e.g. in browser or on user profile and do they want it to laid out like that for all jobs or different layout on different jobs, cc @janfaracik 

----

I like the idea you have for stages / steps / logs in the columns like that and I think we do need a details section but I think it's taking up too much room there.

I wonder if it can be either above the logs or as a pseudo-step, i.e. we add our own step to every stage / possibly steps to add some of that information?

**Comment by timbrown5** [comment]
> I like the idea you have for stages / steps / logs in the columns like that and I think we do need a details section but I think it's taking up too much room there.

Could always go for the split pane approach?

![Screenshot 2022-10-03 at 10 11 44 2](https://user-images.githubusercontent.com/4447764/193769166-d7db2d6a-c1f7-4c62-ae7f-407818b26946.png)

**Comment by timja** [comment]
Yeah that looks good worth trying it out, should definitely look at independent scroll bar though

**Comment by mPokornyETM** [comment]
can you add in the '<stage> - Steps' part a button 'Jump to last step' Will be helpful in case of  many steps.
And the selected step more visible. Like 120 % size or more contrast color, or make 2px margin or what ever.

ps: the same effect shall be done also for stages.

**Comment by timbrown5** [comment]
I realise the original purpose was to surface stage details. I have a mock-up using tool tips here: https://github.com/timbrown5/pipeline-graph-view-plugin/pull/new/console-stage-tooltip

I think the issue will be getting the information (it's a jelly component in the graph view).

Here's a screenshot:
![Screenshot 2022-10-04 at 10 38 39](https://user-images.githubusercontent.com/4447764/193787902-931f7d51-4021-44ee-a11b-50a1f76b1341.png)

**Comment by timja** [comment]
What is the details when below the stages? in the left column?

**Comment by mPokornyETM** [comment]
I is possible to organize some short call?

**Comment by timbrown5** [comment]
> What if the details went below the stages? in the left column?

![Screenshot 2022-10-04 at 10 38 39](https://user-images.githubusercontent.com/4447764/193824459-ad736fce-95ed-4886-9567-394770978930.png)

**Comment by timja** [comment]
Yeah I meant not as a pop out, seems a bit odd to me as it's obscuring the log

**Comment by timbrown5** [comment]
> It's a little bit funky due to the expanding TreeItem.

That said, this can probably be fixed with `anchorEl` so it's more a case of deciding what behaviour you expect: should it overlap items in the list (which is the current focus) or the console (which assumedly isn't)?
Should it be a tooltip at all (or like @mPokornyETM said) should the console view list the details in the log section when a stage is selected?

**Comment by timja** [comment]
Did you think about a pseudo step option?

Stage information
Step information

something like that, which is added with more details ?

----

or as the empty state for when you click on a stage

**Comment by timbrown5** [comment]
> Did you think about a pseudo step option?
> 
> Stage information Step information
> 
> something like that, which is added with more details ?
> 
> or as the empty state for when you click on a stage

I assume this is in relation to:

> details are hardcoded (need a new API endpoint?).

I hadn't considered that, not 100% sure how that would look (would you need a subclass of PipelineStage)?
I was thinking either:
- a new API call (similar to `tree` and `allSteps` - I guess `stageDetails`. This would allow to keep StageInfo class the same between both views, but allow for the Pipeline view to get more data.
- update the PipelineStage class to contain this information (seems like it might be useful elsewhere)?

Re: tooltip, there is always the option to make it slightly transparent 🤷.
![Screenshot 2022-10-04 at 14 23 28](https://user-images.githubusercontent.com/4447764/193831979-72402315-46ec-494e-b87d-32e09477817b.png)

**Comment by timbrown5** [comment]
Added a draft PR incase it helps.

**Comment by mPokornyETM** [comment]
Why as tooltip? I think it will be better, whe you show instead of 'select a node to view console output '

**Comment by timbrown5** [comment]
My thinking was that you might also want that info for steps.

**Comment by timbrown5** [comment]
Could add a header to the console section which lists some details, should
only lose a line or two of console output. Then it can be available for
stages and steps.
If the step names get truncated then the tooltip could show the full step
name.

**Comment by timja** [comment]
Sounds like worth trying

**Comment by timbrown5** [comment]
> Sounds like worth trying

Something like this:
![Screenshot 2022-10-04 at 14 23 28](https://user-images.githubusercontent.com/4447764/195578087-d4be20fa-44ed-4d89-afb0-9fc8c87bed5f.png)

**Comment by mPokornyETM** [comment]
looks good

**Comment by timja** [comment]
yeah looks nice with a bit of polish for spacing / alignment!

**Comment by timbrown5** [comment]
An alternative is as a footer (seems like it would be a bit more out of the way). Could even make it collapsable.

<img width="1217" alt="Screenshot 2022-10-13 at 14 40 30" src="https://user-images.githubusercontent.com/4447764/195613166-b0a91023-0582-483e-844c-ee43ffd0fa2f.png">

**Comment by timja** [comment]
first too me as well

**Comment by timbrown5** [comment]
Exaple Stage:
![Screenshot 2022-10-14 at 13 45 22](https://user-images.githubusercontent.com/4447764/195850408-cb1f178c-61e2-44cb-a0f4-87cdb47e7300.png)

Example step.
![Screenshot 2022-10-14 at 13 49 47](https://user-images.githubusercontent.com/4447764/195851009-9a59859b-c033-411f-a49c-b042902cf627.png)

**Comment by timbrown5** [comment]
> Looks nice but it would be good to get some step details
Are you saying you would like that section to be available for steps and stages?

I have added some additional fields, as per:
>Stage 'Install WinCC OA'
>Started 18 min ago
>Took 9 min 31 sec
>Status : (Success / Failed / Unstable ..)
>Link to last one step (in my case I have ~ 100 steps)

![Screenshot 2022-10-14 at 14 44 58](https://user-images.githubusercontent.com/4447764/195862145-c4741f06-3657-4bb2-a245-1b157813488e.png)

**Comment by timja** [comment]
nice but what about step timing? e.g. good to know if my shell step took 5s or 1hr. (non blocking of course)

**Comment by timbrown5** [comment]
Steps would need a layout to reduce the space :/.

**Comment by timbrown5** [comment]
Stage Summary:
<img width="1160" alt="Screenshot 2022-10-17 at 10 45 26" src="https://user-images.githubusercontent.com/4447764/196146126-ae45f7ea-e871-45da-9740-04260fbb1ada.png">

Step summary:
<img width="1140" alt="Screenshot 2022-10-17 at 10 45 21" src="https://user-images.githubusercontent.com/4447764/196146108-68178e0c-30de-45b8-8d50-6738d473ab43.png">

**Comment by timbrown5** [comment]
This timing is obviously wrong 😬 
> Step summary: <img alt="Screenshot 2022-10-17 at 10 45 21" width="1140" src="https://user-images.githubusercontent.com/4447764/196146108-68178e0c-30de-45b8-8d50-6738d473ab43.png">

**Comment by mPokornyETM** [comment]
Or you branch is parent-of-grandpa-of-git ;-)

**Comment by timja** [comment]
looks nice!
