### ISSUE TITLE
Show user depends information pipeline-console-tree

### ISSUE THREAD

**Issue by mPokornyETM** [jenkinsci/pipeline-graph-view-plugin#147]
### What feature do you want to see added?

As you can see here
![image](https://user-images.githubusercontent.com/89339813/193462465-a0eb8047-5e48-444e-972a-0dae0cecf2ea.png)
it is really hard to understand this steps (also for admins, who cares about the pipes)

Therefore it will be very helpful, when the pipeline-console tree can show more user depends information.
**icon**
I know, that the step as well has no Icon, but the plugin *must* have some icon. Maybe we can use that icons per default.
Other way is to upload icons in to jenkins-instance and use this.
It will be more easy to see, what does the step.
ex: most user does not see any difference between stage and step. And I will not explain to everybody in my company what it means.
I think it will be enough to make some extension-point for this feature. So the plugin maintainers can care about that in the plugin self.

**description**
 this can be used as tooltip and / or in the right output *field*

**name**
to overwrite the current step name

as you can see this echo output makes no sense here.
![image](https://user-images.githubusercontent.com/89339813/193463142-da24a949-a35c-4bc0-8d1a-81326f5332b8.png)
In my case I want to see only:
*prepare node: RHEL8_2NwCard_02 opts*

**Comment by timja** [comment]
To start with I think we could style stages differently? and then maybe limit the step label length?

**Comment by timbrown5** [comment]
Looking through the code, the displayName is ultimately determined by:
```
    public static String getDisplayName(@Nonnull FlowNode node) {
        ThreadNameAction threadNameAction = node.getAction(ThreadNameAction.class);
        return threadNameAction != null
            ? threadNameAction.getThreadName()
            : node.getDisplayName();
    }
```

This actually asks the steps for their display name (via a LabelAction or falling back to getDisplyName for their particular class of action):
https://github.com/jenkinsci/workflow-api-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/graph/FlowNode.java#L255

As such it's already possible to change this behavior upstream (I'm sure this isn't the only place affect by the verbose output. Out of interest, how is it displayed in flowGraphTable? ('Print messag' link in the sidebar).
![Screenshot 2022-10-03 at 09 17 48](https://user-images.githubusercontent.com/4447764/193531506-9ebd309d-a6ca-448d-b902-a08625cf3633.png)

> To start with I think we could style stages differently?

Steps are currently underlined, but there is definitely more that could be done. Any ideas how to better highlight this (e.g. icon, bold text, different font style)?

> and then maybe limit the step label length?
I've thought about this, but not done it. I'm not sure how short to make them or how to truncate. For example we have a Shell step line:

```
#!/bin/bash set -xe export PATH=${PATH}:/home/ubuntu/venvs/user_setup/bin:/home/ubuntu/bin:/home/ubuntu/venvs/view/bin echo '${STUFF}' > /opt/jenkins/workspace/product/product_ci_ubuntu_18_04_debug_unprivileged/stuff - Shell Script
```

If we truncate at the start (as OP suggested) we get:
```
#!/bin/bash set -xe export PATH=${PATH}:/home/ubuntu/venvs/user_setup/bin:/home... - Shell Script
```
Which isn't very meaningful (there are other lines that do the same).

That suggests we could either truncate the in the middle:
```
#!/bin/bash set -xe export PATH=${PATH}...u_18_04_debug_unprivileged/stuff - Shell Script
```

or are the end:
```
...jenkins/workspace/product/poplar_ci_ubuntu_18_04_debug_unprivileged/stuff - Shell Script
```

Any ideas on how to improve this would be welcome.

**Comment by timbrown5** [comment]
> > To start with I think we could style stages differently?
> 
> Steps are currently underlined, but there is definitely more that could be done. Any ideas how to better highlight this (e.g. icon, bold text, different font style)?

A slight aside, do you think that step text should be block aligned?
I.e. this:
![193463142-da24a949-a35c-4bc0-8d1a-81326f5332b8](https://user-images.githubusercontent.com/4447764/193533022-b35cc24d-9233-46f3-a5de-d41bee94cf84.png)

Instead of this:
![193463142-da24a949-a35c-4bc0-8d1a-81326f5332b8](https://user-images.githubusercontent.com/89339813/193463142-da24a949-a35c-4bc0-8d1a-81326f5332b8.png)

**Comment by mPokornyETM** [comment]
About truncate the text. It loads to same like here
![image](https://user-images.githubusercontent.com/89339813/193533648-56165a87-3bd7-4104-8a0a-de89dd602e70.png)

There are 3 different stages but for the user it looks to be the same. It helps only mouse-over event, which is really strange (and sometimes does not works).

Maybe split output by '\n' character? Some think like this
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Donec pulvinar vestibulum risus id consequat. Aenean luctus placerat nunc eget pellentesque. Ut condimentum tortor sed mauris accumsan, id condimentum nisi consectetur. Pellentesque erat odio, accumsan eget commodo ultricies, blandit non tellus. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Donec eleifend dui tortor, quis aliquam orci ornare quis. Nam tincidunt dui pellentesque vestibulum lacinia. Donec dignissim arcu non accumsan scelerisque. Phasellus vestibulum pretium semper. Nam eget neque gravida, scelerisque lorem eu, laoreet libero. Vestibulum nec augue ultrices, pellentesque sapien non, sagittis elit.
```
will produce only
```
Lorem ipsum dolor sit amet, consectetur adipiscing elit. (...)
```
and the full output shall be shown in log-output field

But this can works only for few steps, like echo();

In the bat() or sh() shall be the 'label' parameter used like mentioned here
https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/144

**Comment by timja** [comment]
It's a problem in blue ocean as well, possible a change just needed for the shell script step.

**Comment by mPokornyETM** [comment]
> It's a problem in blue ocean as well, possible a change just needed for the shell script step.

yes I know, that the same issue is on blue-ocean. I want to create issue / feature-request in the plugin, but there are too much open issues. And I do not like the plugin. It is terrible slow and kill our jenkins instance in many cases (blocking threads ...)

**Comment by timbrown5** [comment]
> yes I know, that the same issue is on blue-ocean. I want to create issue / feature-request in the plugin, but there are too much open issues. And I do not like the plugin. It is terrible slow and kill our jenkins instance in many cases (blocking threads ...)

(Sorry if I'm being dense), which plugin are you referring?

**Comment by mPokornyETM** [comment]
Everything is fine, I want just comment, that this issue is in both plugins (blue-ocean and pipeline-graph-view). That`s acceptable, but maybe it can be changed here. This will be great. When it also effect on blue ocean and it is fixed there too, I am very happy. I just saying, that blue ocean is not the best one choice ;-)

**Comment by timbrown5** [comment]
> ex: most user does not see any difference between stage and step. And I will not explain to everybody in my company what it means.
@mPokornyETM could you have a look at the changes. 
- Steps have been moved to the StageView (right pane)
  - Should prevent confusion between stages and steps.
  - Should allow for more text to be shown than in the TreeView.
  
Also, you should be able to add a `label` to a number of steps (e.g. `sh`) to add a more meaningful name to the step:
Instead of this:
<img width="736" alt="Screenshot 2023-04-12 at 09 31 15" src="https://user-images.githubusercontent.com/4447764/231400814-7a27e3c3-b8f6-44af-b2a7-fb88343a97fa.png">
you can have this:
<img width="740" alt="Screenshot 2023-04-12 at 09 33 03" src="https://user-images.githubusercontent.com/4447764/231400934-d917d57e-ffb9-466c-ab12-275e9a64f571.png">

```
pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello world!'
                sh(
                    label: "Print a long line",
                    script: 'echo "Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"'
                )
            }
        }
    }
}
```

**Comment by timja** [comment]
I think this is resolved, let me know if not
