### ISSUE TITLE
Progressive Console Output

### ISSUE THREAD

**Issue by stuartrowe** [jenkinsci/pipeline-graph-view-plugin#175]
### What feature do you want to see added?

Console output doesn't update when viewing a step. Similarly the pipeline graph doesn't seem to update like it does in Blue Ocean.

In both cases the page needs to be refreshed to see changes.

**Comment by timja** [comment]
ideally I think websockets and falling back to server side events if not supported.

**Comment by timbrown5** [comment]
👍That's what I was thinking too. Do you know any plugins that use the web
sockets?
Trying to get me head around what URL and other voodoo to use to register
the front end with the back.

**Comment by timbrown5** [comment]
And also how to expose a WebSocket in stapler.

**Comment by henryborchers** [comment]
With this, I could finally ditch blue ocean.

**Comment by timbrown5** [comment]
I had a look at this briefly. Seems like we would need to add a build channel (and events) to https://github.com/jenkinsci/pubsub-light-plugin/blob/master/src/main/java/org/jenkinsci/plugins/pubsub/Events.java
Then we can get step started, step  updated (new console output), step finished, maybe stage started, stage updated, stage ended.

**Comment by timbrown5** [comment]
From my limited understanding: the console update could be implemented on its own with a poll (Virrtuoso has a callback for training the bottom of a list).
The issue comes with updating the list of stages and steps as the pipeline is running.
Not sure if there is something we could do utilising stapler callbacks?

**Comment by henryborchers** [comment]
I'm guessing this is a very hard task to do.

**Comment by timbrown5** [comment]
I've considered added the existing poller (the one the graph view uses) to
the console view.

It would need to be careful not to throw away any existing console logs -
might be best to split the step and console log objects to make this easier.

Then we can add a new task to add SSE triggers to all views.

**Comment by timbrown5** [comment]
> I've considered added the existing poller (the one the graph view uses) to
the console view.

This is to say, it should be relatively simple to add polling and improve it with SSE in the future.

**Comment by timbrown5** [comment]
@stuartrowe I believe this is fixed by the log following added in v183.v9e27732d970f.
If not could you update the ticket with additional information/missing features?
