### ISSUE TITLE
Graph not as in Blue Ocean

### ISSUE THREAD

**Issue by PP-DanielB** [jenkinsci/pipeline-graph-view-plugin#18]
### Version report

Jenkins and plugins versions report:

```
Jenkins: 2.289.2
OS: Linux - 5.10.25-linuxkit
---
github-api:1.123
pipeline-input-step:2.12
git:4.7.2
snakeyaml-api:1.29.1
favorite:2.3.3
antisamy-markup-formatter:2.1
blueocean-dashboard:1.24.7
sse-gateway:1.24
copyartifact:1.46.1
jdk-tool:1.5
docker-commons:1.17
plugin-util-api:2.3.0
lockable-resources:2.11
jenkins-design-language:1.24.7
subversion:2.14.4
bouncycastle-api:2.20
jquery3-api:3.6.0-1
forensics-api:1.2.0
blueocean-pipeline-editor:1.24.7
toolenv:1.2
token-macro:2.15
blueocean-events:1.24.7
pipeline-stage-step:2.5
workflow-step-api:2.24
blueocean-display-url:2.4.1
github-branch-source:2.11.1
workflow-aggregator:2.6
workflow-basic-steps:2.23
variant:1.4
blueocean-github-pipeline:1.24.7
sshd:3.0.4
jjwt-api:0.11.2-9.c8b45b8bb173
apache-httpcomponents-client-4-api:4.5.13-1.0
credentials-binding:1.27
durable-task:1.37
matrix-project:1.19
blueocean-rest:1.24.7
workflow-cps-global-lib:2.21
font-awesome-api:5.15.3-3
git-client:3.7.2
extended-choice-parameter:0.82
popper2-api:2.5.4-2
email-ext:2.83
workflow-cps:2.92
jaxb:2.3.0.1
pipeline-github-lib:1.0
blueocean-bitbucket-pipeline:1.24.7
credentials:2.5
branch-api:2.6.4
momentjs:1.1.1
popper-api:1.16.1-2
warnings-ng:9.3.0
cloudbees-bitbucket-branch-source:2.9.9
resource-disposer:0.16
ldap:2.7
analysis-model-api:10.2.5
echarts-api:5.1.2-2
gradle:1.37.1
envinject-api:1.7
pipeline-model-definition:1.8.5
pam-auth:1.6
structs:1.23
ssh-slaves:1.32.0
blueocean-autofavorite:1.2.4
blueocean-git-pipeline:1.24.7
workflow-scm-step:2.13
pubsub-light:1.16
handlebars:3.0.8
scm-api:2.6.4
blueocean-core-js:1.24.7
script-security:1.77
trilead-api:1.0.13
pipeline-model-extensions:1.8.5
workflow-support:3.8
blueocean-pipeline-api-impl:1.24.7
plain-credentials:1.7
jackson2-api:2.12.3
workflow-job:2.41
pipeline-model-api:1.8.5
bootstrap5-api:5.0.1-2
ant:1.11
bootstrap4-api:4.6.0-3
matrix-auth:2.6.7
workflow-api:2.46
blueocean:1.24.7
docker-workflow:1.26
blueocean-config:1.24.7
blueocean-jwt:1.24.7
ace-editor:1.1
junit:1.51
display-url-api:2.3.5
command-launcher:1.6
quality-gates:2.5
pipeline-stage-tags-metadata:1.8.5
authentication-tokens:1.4
caffeine-api:2.9.1-23.v51c4e2c879c8
pipeline-milestone-step:1.3.2
blueocean-web:1.24.7
jquery:1.12.4-1
timestamper:1.13
workflow-multibranch:2.26
blueocean-personalization:1.24.7
pipeline-graph-view:27.vab27f850fea5
cloudbees-folder:6.15
mailer:1.34
pipeline-stage-view:2.19
github:1.33.1
blueocean-commons:1.24.7
handy-uri-templates-2-api:2.1.8-1.0
mapdb-api:1.0.9.0
ecutest:2.27
okhttp-api:3.14.9
blueocean-rest-impl:1.24.7
checks-api:1.7.0
git-server:1.10
ws-cleanup:0.39
blueocean-i18n:1.24.7
htmlpublisher:1.25
pipeline-utility-steps:2.8.0
pipeline-graph-analysis:1.11
ssh-credentials:1.19
custom-tools-plugin:0.8
pipeline-rest-api:2.19
jsch:0.1.55.2
workflow-durable-task-step:2.39
data-tables-api:1.10.25-1
blueocean-pipeline-scm-api:1.24.7
pipeline-build-step:2.13
build-timeout:1.20
```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
Jenkins within Docker image (based on the Jenkins documentation: https://www.jenkins.io/doc/book/installing/docker/) with Windows 10 Enterprise (20H2) and Windows agent via "agent.jar"
```

### Pipeline script

**Based on my real script but simplified:** [pipeline_script.txt](https://github.com/jenkinsci/pipeline-graph-view-plugin/files/6821463/pipeline_script.txt)

### Results

Expected result:

**Blue Ocean**
![blue_ocean](https://user-images.githubusercontent.com/87469510/125754109-0f147d5d-62a8-4752-8a86-7f2110603bd7.jpg)

Actual result:

**Pipeline Graph**
![pipeline_graph](https://user-images.githubusercontent.com/87469510/125754139-7680c077-58db-4ff5-8015-ebca03b1a903.jpg)

**Comment by timbrown5** [comment]
I'm slightly worried that this issue could be open ended.
I have created a gist with an update to the `PipelineGraphApiTest#complexSmokes` test which shows an issue - the graph is wrong when a stage in a parallel block has a child stages.
```
stage('Parallel Stage') {
    parallel {
        stage('Branch A') {
            stages {
                stage('Nested 1') {
                    steps {
                        echo "In stage Nested 1 within Branch C"
                    }
                }
            }
       }
   }
}
```
The graph shows the child of `Parallel Stage` is `Nested 1` and not `Branch A`.
https://gist.github.com/timbrown5/d600d63ad819ebc5a85323f8c75fc160

**Comment by adis-io** [comment]
Sorry for spaming, but is there any demo of using this plugin?
I'm aware of [this](https://ci.jenkins.io/job/Plugins/job/pipeline-graph-view-plugin/job/main/), but it doesn't use parallel stages

**Comment by timja** [comment]
Check the core folder, most of them will use parallel e.g the Jenkins project

it’s using an older version of the plugin currently without the recent fixes

**Comment by adis-io** [comment]
> Check the core folder, most of them will use parallel e.g the Jenkins project
> 
> it’s using an older version of the plugin currently without the recent fixes

Thanks. One more question and I'll leave you alone. Is there any plan to replace or at least make configurable default stage view to with this plugin?

**Comment by timja** [comment]
somewhat yes at some point, I'm working on the build page currently.

<img width="1438" alt="image" src="https://user-images.githubusercontent.com/21194782/189535614-ca6e24a9-fd24-48a1-9561-8bf3858b26c1.png">

and there's a prototype at https://jenkins-redesign.herokuapp.com/project which I'm looking at experimenting with in this plugin

**Comment by adis-io** [comment]
Cool. Thanks for info
