### ISSUE TITLE
Allow to share a link to a specific stage/step of the Pipeline Console view.

### ISSUE THREAD

**Issue by jamoralp** [jenkinsci/pipeline-graph-view-plugin#195]
### What feature do you want to see added?

I would find it very useful to be able to create links to specific stages/step sections of the Pipeline Console view so that I can share them with someone else pinpointing the specific step/stage in which the pipeline failed, for instance.

**Comment by timbrown5** [comment]
The line numbers in the console view should be clickable and should update the URL to one that is shareable - or you can right-click to copy the link too.
This should give you a link like https://my-jenkins/jenkins/job/my-job/2/pipeline-console/?selected-node=7#log-4

If this doesn't suit your workflow, could you describe your use-case?

**Comment by timja** [comment]
closing given no reply and this already works as far as I know
