### ISSUE TITLE
Logs touching timestamp with ansi color

### ISSUE THREAD

**Issue by timja** [jenkinsci/pipeline-graph-view-plugin#200]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

-

### Reproduction steps

The script that generates this is https://github.com/hmcts/cnp-jenkins-library/blob/9385546f76abbf8820037b6b9eaa3695498e0432/resources/uk/gov/hmcts/helm/aks-debug-info.sh

It's a java stacktrace with ansi color highlighting

### Expected Results

A bit of space in between timestamp and text, see blueocean:

![image](https://user-images.githubusercontent.com/21194782/203509009-d5caaab5-ffa9-4e58-a4ac-5b69028c8c6b.png)

### Actual Results

![image](https://user-images.githubusercontent.com/21194782/203509039-b8153467-003d-4564-9172-95eeadc6be67.png)

**Comment by timbrown5** [comment]
Do you happen to have a Pipeline that repos this?
I assume this is because the raw HTML is setting custom CSS that's affecting the formatting.
Are you able to give a link to the build, or some detail about the span that txt belongs to?

**Comment by timja** [comment]
the CI instance is internal. No pipeline right now

Here's an example node:

![image](https://user-images.githubusercontent.com/21194782/203966611-1398939c-70c1-45be-b1da-69ae38d13d47.png)

```html
<div class="console-output-item"><div class="console-output-line-anchor" id="log-13"></div><div class="console-output-line"><a class="console-line-number" href="?selected-node=173#log-13">13</a><div><span class="timestamp"><b>09:14:50</b> </span><span style="display: none">[2022-11-23T09:14:50.278Z]</span> </div><span class="ansi-fg-3">34m         Warning   BackOff                           pod/plum-recipe-backend-pr-620-java-77c99cc579-vvjhj      Back-off restarting failed container</span></div></div>
```

**Comment by timbrown5** [comment]
Not sure if `15px` is too much of a gap?
![Screenshot 2022-11-25 at 16 24 40](https://user-images.githubusercontent.com/4447764/204025264-79c8398d-ddde-4de7-bcc9-271745344948.png)

**Comment by timja** [comment]
looks fine
