### ISSUE TITLE
PipelineConsoleView: children of a node as shown as sequential steps, and not lower level tree items.

### ISSUE THREAD

**Issue by timbrown5** [jenkinsci/pipeline-graph-view-plugin#22]
The tree returned by the `tree` REST API call should be a tree representation, but it is a graph (it's just a copy of the `graph` rest call).
FlowGraphTable does something similar when ordering the rows for its table:
https://github.com/jenkinsci/workflow-support-plugin/blob/master/src/main/java/org/jenkinsci/plugins/workflow/support/visualization/table/FlowGraphTable.java#L126

**Comment by timbrown5** [comment]
There are a couple of issues here:
- Using the graph visitor creates and graph, and not a table, structure.
- The Step Visitor gets all the steps below a node (not just the children of that node) - this means steps are duplicated in the tree view.
- The FrontEnd doesn't seem to call `steps` API for the lowest level stages (they are always empty).

There are better long term fixes for the (which are likely more efficient) it should be possible to use a custom AbstractFlowScanner (or try DepthFirstScanner) to get the list of steps. The docs for AbstractFLowScanner list a similar use case:
> Suggested uses:
>
> ...
> - Find the first node with an ErrorAction before a specific node
> - Scan through all nodes *just* within a block

**Comment by timja** [comment]
I'm missing a bit of context, what's the affect / benefit you will gain?

Better nesting in the log view?

**Comment by timbrown5** [comment]
> I'm missing a bit of context, what's the affect / benefit you will gain?
>
> Better nesting in the log view?
In short yes.

Using the pipeline you provided [here](https://github.com/jenkinsci/pipeline-graph-view-plugin/pull/15#issuecomment-865661205) as an example, I get this:
![Screenshot 2021-07-22 at 13 13 49](https://user-images.githubusercontent.com/4447764/126637411-718efcb2-b3f1-42f1-959b-18a1bf59a27a.png)
The issues are:
- All the steps are placed under `Parallel Stage`, when they should be under their respective branches (e.g. the first two should be under `Branch A`. `Parallel Stage` should have no child steps.
-- This behaviour seems to be a culmination of these two issues (from above)
> - The Step Visitor gets all the steps below a node (not just the children of that node) - this means steps are duplicated in the tree view.
> - The FrontEnd doesn't seem to call steps API for the lowest level stages (they are always empty).
- `Branch C` is missing.
- `Nested 1` should e under the missing `Branch C` (and I think it has `Branch C`'s ID).
- `Nested 2` is missing.

**Comment by timbrown5** [comment]
> The FrontEnd doesn't seem to call steps API for the lowest level stages (they are always empty).
This should be fixed by #23

**Comment by timbrown5** [comment]
I have updated the PR with something close to a fix:
![Screenshot 2021-07-24 at 09 44 47](https://user-images.githubusercontent.com/4447764/126863002-8a1dbd4e-48d3-4e40-aa71-26ccfebb26ca.png)

The code to add the steps to the correct stage/parallel block is faulty - it adds parallel block steps to a stage inside the parallel block, not the parallel block itself. I have tried to fix it but don't have much experience with parsing the DAG.
