### ISSUE TITLE
Add Pipeline exceptions to console view

### ISSUE THREAD

**Issue by timbrown5** [jenkinsci/pipeline-graph-view-plugin#221]
### What feature do you want to see added?

If a Pipeline has a syntax error the console view won't display this - as it's not thrown by a step. This means the user needs to go to the full console to view this.

In this case, we could add an additional Stage - which represents the end of the Pipeline - called `Pipeline error` (https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/213#issuecomment-1439168149). Then we can use something like this to assign a new step to that node - which would allow the retrieval of the stack trace:
https://github.com/jenkinsci/pipeline-graph-view-plugin/pull/217/files#diff-db0a2326fbed44b063bd8441a0dc32b9c19a86a40db4694f8f8258d382bf64fdR244

**Comment by timbrown5** [comment]
Related to: #217

**Comment by timja** [comment]
Isn't this implemented?

Tested with:
```
stage('hello') {
    echo "hello"
    adfas
}
```

![Uploading image.png…]()

**Comment by timbrown5** [comment]
Mostly. There will still be an issue if you have an exception outside of a
stage (might be the same if you have a step outside of a stage too).
Might need a catch all tree node that appears if there are orphaned steps
or exceptions.

**Comment by timja** [comment]
Step outside stage seems okay at least for a simple one it gets attached to the nearest stage:

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/21194782/221382399-15bc0d6e-c145-4c0e-afe9-d9a9a10d1661.png">

No stage doesn't work (and should):
<img width="1256" alt="image" src="https://user-images.githubusercontent.com/21194782/221382414-6641baec-5a82-43b7-a141-10ca69e737c9.png">

Syntax error outside stage seems fine too:
<img width="1249" alt="image" src="https://user-images.githubusercontent.com/21194782/221382433-8790f2c2-86db-466a-853c-16aa5d290c96.png">

```
stage('hello') {
    echo 'world'
}

abcd
```

**Comment by timbrown5** [comment]
Ahh, that's good 👍.

**Comment by timbrown5** [comment]
Seems like it's handled.
