### ISSUE TITLE
Propagate status of nested stages to parent stage in console view

### ISSUE THREAD

**Issue by x3ntrix** [jenkinsci/pipeline-graph-view-plugin#222]
### What feature do you want to see added?

When working with parallel or otherwise with sub-stages, e.g.:
```
pipeline 
{
    agent any
    
    stages 
    {
        stage('ParentStage') 
        {
            stages
            {
                stage('SubStageA')    
                {
                    steps
                    {
                        echo 'SubStageA'
                        bat 'exit 1'
                    }
                }
                
                stage('SubStageB')    
                {
                    steps
                    {
                        echo 'SubStageB'
                    }
                }
            }
        }
    }
}
```
the Pipeline Console view looks like this when a sub-stage fails:
![grafik](https://user-images.githubusercontent.com/11992649/220898456-d3986c6f-bc83-4b3c-9cd4-9467c58b2cbe.png)

We expected that the ParentStage is also marked as failed in this case and think that it would be a nice improvement to do so. Or is there a valid reason for the current behavior?

**Comment by timbrown5** [comment]
We would need to be careful, as I don't think we get information about caught exceptions. I'm surprised the FlowEcexution graph doesn't do this already.
I think we can do this by finding exceptions at the end of stages, storing them and using that to update the stage state when we get to the start node.

**Comment by timbrown5** [comment]
Noticed a similar thing with a running stage - the parent is completed before the children have completed.
<img width="647" alt="Screenshot 2023-03-09 at 22 27 57" src="https://user-images.githubusercontent.com/4447764/224174923-845e14af-a6a2-4a53-9515-3e6b430995bb.png">
This could potentially be fixed by returning the end node of a stage/block instead of the start node.
