### ISSUE TITLE
Pipeline Graph doesn't show child stages for Scripted Pipeline

### ISSUE THREAD

**Issue by timbrown5** [jenkinsci/pipeline-graph-view-plugin#228]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Jenkins: 2.361.4
Pipeline Graph View Plugin: 157.vd6123e1b_a_e2e

### Reproduction steps

When using this scripted Pipeline I am expecting the graph to show a `World` stage as a sibling of `Hello`, but it doesn't get displayed at all.
```
stage("Hello") {
    stage("World") {
        echo("Hello, world!")
    }
}
```

### Expected Results

I expect the same graph as this declarative Pipeline:
```
pipeline {
    agent any

    stages {
        stage('Hello') {
            stages {
                stage('World') {
                    steps {
                        echo 'Hello World'   
                    }
                }
            }
        }
    }
}
```
<img width="896" alt="Screenshot 2023-02-24 at 13 37 05" src="https://user-images.githubusercontent.com/4447764/221192117-92424ed4-5a12-43d3-81d8-0717d3872988.png">

### Actual Results

I don't see the 'world' stage at all (this is also true for the Pipeline Console).
<img width="879" alt="Screenshot 2023-02-24 at 13 47 36" src="https://user-images.githubusercontent.com/4447764/221194350-6db88d7d-b656-4f77-9ba2-76d73148fdbd.png">

### Anything else?

The error seems to be that nested scripted stages are skipped: 
https://github.com/jenkinsci/pipeline-graph-view-plugin/blob/main/src/main/java/io/jenkins/plugins/pipelinegraphview/utils/PipelineNodeGraphVisitor.java#L221

This was introduced here: https://github.com/jenkinsci/blueocean-plugin/pull/1778  (maybe scripted Pipelines didn't support this in the past?)

When I remove this section I get the expected graph:
<img width="889" alt="Screenshot 2023-02-24 at 13 53 19" src="https://user-images.githubusercontent.com/4447764/221195492-352cd1d1-16aa-4739-8f5c-cd25d3810063.png">

**Comment by timja** [comment]
Seems they intentionally didn't support this without giving any reasoning:
https://github.com/jenkinsci/blueocean-plugin/pull/1778#pullrequestreview-141157163

"We do not support this but it works just fine"...

**Comment by timbrown5** [comment]
I guess the quests is, does this plugin want to support it? (seems like a common use case)?

**Comment by timja** [comment]
I would enable it and then if he hit issues we can turn it off later.
