### ISSUE TITLE
"Details" is IMHO not a reasonable name to link from "Console" to "Pipeline Graph"

### ISSUE THREAD

**Issue by jimklimov** [jenkinsci/pipeline-graph-view-plugin#243]
### What feature do you want to see added?

Given that the Console view refers to hundreds of nodes and individual step logs truly in detail, the much less cluttered Graph is, perhaps, an "Overview"? Certainly not "Details" material :)

**Comment by timbrown5** [comment]
Do you have a recommendation for a clearer name?
