### ISSUE TITLE
Document (implement?) a way to set the Jenkins-instance "Default" Notification URL to view links from GitHub build results etc.

### ISSUE THREAD

**Issue by jimklimov** [jenkinsci/pipeline-graph-view-plugin#245]
### Describe your use-case which is not covered by existing documentation.

I can't find a way to set the Jenkins-instance "Default" Notification URL (something that can be set in each user's configuration to their taste - including a "Default" choice that I can't modify site-wide). Is it named differently in Global config, or not in it, or just missing altogether? :)

Note this differs from possibly setting something for Anonymous user in particular. I want to set site-wide defaults for all logged-in users to see specifically PGV, BO or Classic unless they explicitly choose something other than "Default" in their account settings.

**Comment by lemeurherve** [comment]
There is no doc for that on jenkins.io but this one from CloudBees is showing how to configure it: https://docs.cloudbees.com/docs/cloudbees-ci-kb/latest/client-and-managed-masters/how-to-point-notification-links-to-classic-jenkins-path-rather-than-to-blueocean-endpoint

Just tried the User configuration, it worked fine.

**Comment by dwnusbaum** [comment]
The ability to set a global default notification URL was just implemented in https://github.com/jenkinsci/display-url-api-plugin/pull/293 and released in [`display-url-api` 2.3.9](https://github.com/jenkinsci/display-url-api-plugin/releases/tag/display-url-api-2.3.9). The new section in the global configuration is called "Default notification URL" (mirrors "Notification URL" on the user configuration page).

@timja just fyi I think this issue can be closed.
