### ISSUE TITLE
Wrong icon in pipeline graph overview

### ISSUE THREAD

**Issue by NotMyFault** [jenkinsci/pipeline-graph-view-plugin#276]
### Jenkins and plugins versions report

ci.jenkins.io

### What Operating System are you using (both controller, and any agents involved in the problem)?

ci.jenkins.io

### Reproduction steps

Open a pipeline graph and notice the three dots missing.

### Expected Results

The blue symbol is the same as on the legend tab and title on the page.

### Actual Results

The symbol misses the three dots:

![Screenshot 2023-05-03 at 21 59 26](https://user-images.githubusercontent.com/13383509/236034911-e0910a66-a1aa-4edd-bed1-ea844627a455.png)

**Comment by disisisid** [comment]
Hi @NotMyFault

I was able to fix it.
![Screenshot](https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/29148054/d6cba41d-29f2-403a-a665-c7737158d900)

Please assign the issue to me.
Thanks

**Comment by NotMyFault** [comment]
> Hi @NotMyFault
> 
> I was able to fix it. ![Screenshot](https://user-images.githubusercontent.com/29148054/237769799-d6cba41d-29f2-403a-a665-c7737158d900.png)
> 
> Please assign the issue to me. Thanks

Just create a PR.
