### ISSUE TITLE
Pipeline Overview should fill the entire page

### ISSUE THREAD

**Issue by lppedd** [jenkinsci/pipeline-graph-view-plugin#277]
### What feature do you want to see added?

This is how *Pipeline Overview* is displayed on 2K resolution.  
From a usability standpoint it should fill the entire screen.  
Also, not sure why there is no menu on the left, is it intentional?

![image](https://user-images.githubusercontent.com/19871649/236649235-08054e92-2f2b-4dcf-a445-6a44837c9bda.png)

**Comment by croydondias** [comment]
Totally agree. For large complex pipelines, a user is forced to pan around in a small viewport. Better use of the white space would help with this.

**Comment by lemeurherve** [comment]
@lppedd @croydondias PTAL at https://github.com/jenkinsci/pipeline-graph-view-plugin/releases/tag/202.v6da_a_9e590325 including https://github.com/jenkinsci/pipeline-graph-view-plugin/pull/299, it should address most of this issue.

**Comment by lppedd** [comment]
@lemeurherve thanks! Now it looks way better, and it's actually useful.  
We can close imo.

![image](https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/19871649/038100a1-82e2-4ddd-9952-b560a9f1f220)
