### ISSUE TITLE
Add option to render stages view on main pipeline page

### ISSUE THREAD

**Issue by akrapfl** [jenkinsci/pipeline-graph-view-plugin#282]
### What feature do you want to see added?

As a jenkins user, I would like an option to set the `pipeline-graph-view` as the default view for a pipeline job, replacing the `pipeline-stage-view`, so that I have a more modern, and parallel-friendly view as my main entrypoint into my job.

`pipeline-graph-view` is ready for prime time.  What better way to accomplish that than adding a flag to allow the current `stages` link on the left of the primary page to be rendered in place of the old `stage view`.

Ideally the implementation would be a declarative option specified in the jenkinsfile.

```
pipeline {
  agent any
  options{
    useGraphView(true)
  }
...
}
```

Alternatively, a global setting for the controller could work.

**Comment by tra-github** [comment]
Just posted the same enhancement request

**Comment by reid-p** [comment]
+1

**Comment by mfumita** [comment]
+1

**Comment by waclawski** [comment]
+1

**Comment by timja** [comment]
is there a reason you want it per pipeline rather than just global?

(contributions welcomed for this)

**Comment by tra-github** [comment]
> is there a reason you want it per pipeline rather than just global?
> 
> (contributions welcomed for this)

As far as I'm concerned, having the pipeline-graph-view as default for all the pipelines is perfect.

**Comment by akrapfl** [comment]
I don't think I have a problem with it implemented globally (without configuration per pipeline).  Really just looking for an option to retire stage-view.  The recent addition of #293 seems consistent with implementing this globally.

**Comment by Jason-Lam-1** [comment]
This would be great.
It would be great to show also the changes, overall runtime and Stage runtime. Those are useful information to have at a glance.

**Comment by skystebnicki** [comment]
I know I'm a bit late to the party on this one, but I'd like to +1 the request. It would be really great for us if we could utilize this more modern and informative view on the main job page - and even better if we can do it for all pipelines.

**Comment by skystebnicki** [comment]
Amazing! Thank you.
