### ISSUE TITLE
Make the graph view the default view

### ISSUE THREAD

**Issue by tra-github** [jenkinsci/pipeline-graph-view-plugin#287]
### What feature do you want to see added?

I would like a similar behavior as the stage view plugin, build graph should be shown by default in the jenkins UI without having to click on "stages".

**Comment by SaturnIC** [comment]
Why did you close this?
It is still not done!

**Comment by timja** [comment]
It is available if you go to the `Appearance` system configuration page you can enable it there

**Comment by SaturnIC** [comment]
Ah thank you !

**Comment by avnerv** [comment]
> It is available if you go to the `Appearance` system configuration page you can enable it there

Could you share how we can manage it  via JCasC?
