### ISSUE TITLE
ConsoleView: Make steps (and stages) indicate their status

### ISSUE THREAD

**Issue by timbrown5** [jenkinsci/pipeline-graph-view-plugin#29]
Currently, all the tree items in the ConsoleVIew look the same. It would be nice for them to be redered differently depending on their status (e.g. including a status Icon, or marking the left hand border green/yellow/red depending on status).

The status should already be available as `state` from:
https://github.com/jenkinsci/pipeline-graph-view-plugin/blob/main/src/main/frontend/pipeline-graph-view/pipeline-graph/main/PipelineGraphModel.tsx#L46 (stage)
and
https://github.com/jenkinsci/pipeline-graph-view-plugin/blob/main/src/main/frontend/pipeline-console-view/pipeline-console/main/DataTreeView.tsx#L26 (step)

I hope this will be as simple as adding a class for each state in the CSS and setting that class when the item is added to the DataTreeVIew.

**Comment by timja** [comment]
Will be fixed by https://github.com/jenkinsci/pipeline-graph-view-plugin/pull/131
