### ISSUE TITLE
Cursor should be pointer on .step-detail-group elements

### ISSUE THREAD

**Issue by bencehornak-gls** [jenkinsci/pipeline-graph-view-plugin#295]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
Jenkins: 2.414.1
OS: Linux - 3.10.0-1160.81.1.el7.x86_64
Java: 11.0.20 - Eclipse Adoptium (OpenJDK 64-Bit Server VM)
---
pipeline-build-step:505.v5f0844d8d126
pipeline-graph-analysis:202.va_d268e64deb_3
pipeline-graph-view:198.v0844db_6ca_554
  ```

  **Note:** I have removed other plugins to not compromise our 

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

N/A

### Reproduction steps

1. Open a build
2. Open the Pipeline Console
3. Hover your mouse over a step

### Expected Results

The cursor type should switch to `pointer` indicating that this is a clickable surface

### Actual Results

The cursor remains on its default value, which is
- `text`, if you bring your cursor over the step text
- `default`, when you are just above the green area, but not the text

![image](https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/104418584/90210ceb-cffb-4fa7-b40e-2088ea20e05d)

(Can't make a screenshot with my cursor on it, but imagine these cursor types on the screenshot 😄)

### Anything else?

For different cursor types refer to the [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/cursor#keyword)

Adding the following rule should solve it:
```css
.step-detail-group {
  cursor: pointer;
}
```

https://github.com/jenkinsci/pipeline-graph-view-plugin/blob/9e27732d970f7fb4113feaa2b5c5f8b4994e0580/src/main/frontend/pipeline-console-view/pipeline-console/main/pipeline-console.scss#L298-L305

**Comment by timja** [comment]
Did you want to send a pull request?

**Comment by bencehornak** [comment]
@timja just opened one with my personal GH account
