### ISSUE TITLE
on some other actions page goto the pipeline-graph page the url wrong

### ISSUE THREAD

**Issue by mamh2021** [jenkinsci/pipeline-graph-view-plugin#3]
### Version report

Jenkins and plugins versions report:

```
I clone the code and checkout this commit 7d78dd6b1eae64ea4c3046e438e02f0d63858c35
and run mvn -Dpermissive-script-security.enabled=true -DskipTests=true -Dhost=0.0.0.0 package hpi:run


```

- What Operating System are you using (both controller, and any agents involved in the problem)?

```
I clone the code and run mvn 
mvn -Dpermissive-script-security.enabled=true -DskipTests=true -Dhost=0.0.0.0 package hpi:run

```

### Reproduction steps
on replay page, the  "pipeline-graph" page link is "http://ip:8080/jenkins/job/test_pipeline/3/replay/pipeline-graph"
on "Restart from Stage", the link is http://ip:8080/jenkins/job/test_pipeline/3/restart/pipeline-graph

http://ip:8080/jenkins/job/test_pipeline/3/flowGraphTable/pipeline-graph
http://ip:8080/jenkins/job/test_pipeline/3/ws/pipeline-graph

![图片](https://user-images.githubusercontent.com/16930340/109960024-31eee800-7d23-11eb-85d9-d9bd66a69ad6.png)

- Step 1...
- Step 2...

### Results

Expected result:

Actual result:

**Comment by timja** [comment]
Thanks for the report, contributions welcome, or I'll take a look when I get a chance

**Comment by darxriggs** [comment]
It seems that this can only be reproduced with a subset of all available actions.

Examples:

Action|URL
---|---
Git Build Data|`.../job/<job name>/<build number>/git/`
Pipeline Steps|`.../job/<job name>/<build number>/flowGraphTable/`
Workspaces|`.../job/<job name>/<build number>/ws/`

It seems that they have the trailing `/` in common.
