### ISSUE TITLE
Matrix labels cut-off

### ISSUE THREAD

**Issue by timja** [jenkinsci/pipeline-graph-view-plugin#31]
### Reproduction steps

See pipeline in https://www.jenkins.io/blog/2019/11/22/welcome-to-the-matrix/

![image](https://user-images.githubusercontent.com/21194782/126991422-99cb1c28-9545-484c-a100-6fcf8cb1b622.png)

Labels are cut-off, you can hover over them to get a tool-tip, but that's poor UX.

This is an inherited defect from blue ocean but we should fix it here since it's easier for us.

### Results

Expected result:

Probably move text either below or above?

**Comment by lemeurherve** [comment]
This one, so much!

**Comment by timja** [comment]
Maybe works in that case but my original PR tried to do something similar and it looked bad in many cases. There’s just not enough room there for it
