### ISSUE TITLE
Use step display name in tree 

### ISSUE THREAD

**Issue by timja** [jenkinsci/pipeline-graph-view-plugin#32]
### Feature Request

Steps like shell script can customise what their step displays as in the UI.
Currently in our logs it's just showing 'Shell Script' but in Blue ocean it says:

```
mvn clean compile - Shell Script
```

![image](https://user-images.githubusercontent.com/21194782/126993961-8d06b903-317b-40a2-ab49-7ef139e983ff.png)

![image](https://user-images.githubusercontent.com/21194782/126994003-ebbc718d-6547-45e0-8dae-d751585047ca.png)

**Comment by timja** [comment]
cc @timbrown5

**Comment by timbrown5** [comment]
Just seen this, I have put up #38 (although it follows the Stage View style of putting the test type first (it's simple to swap though).

**Comment by timja** [comment]
Fixed in https://github.com/jenkinsci/pipeline-graph-view-plugin/pull/38
