### ISSUE TITLE
NPE when accessing View as Plain text link

### ISSUE THREAD

**Issue by mawinter69** [jenkinsci/pipeline-graph-view-plugin#323]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
pipeline-graph-view 214.v6e2833d3fea_9
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

windows, linux

### Reproduction steps

1. create following pipeline:
```
p = [:]
p["parallel1"] = {
    node() {
        stage("stage 1") {
            echo "parallel 1"
        }
    }
}

p["parallel2"] = {
    node() {
        stage("stage 2") {
            echo "parallel 1"
        }
    }
}

parallel p
```

2. run the pipeline
3. visit `console view`and navigate to `parallel1`
4. click on the `View as plain text`link

![image](https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/17767050/a67440e5-156a-4c44-a2b2-4d869beb31cf)

### Expected Results

I see the logs of all inner steps (or maybe also nothing)

### Actual Results

Angry Jenkins

**Comment by timja** [comment]
The logs aren't being found, I haven't dug deeper into why but this will stop an error message for now anyway: https://github.com/jenkinsci/pipeline-graph-view-plugin/pull/324
