### ISSUE TITLE
Pipeline Console's left pane should allow scrolling

### ISSUE THREAD

**Issue by nre-ableton** [jenkinsci/pipeline-graph-view-plugin#342]
### What feature do you want to see added?

We have some pipelines with _a lot_ of parallel rows. This particular build has 92, but the Pipeline Console only shows the first ~36:

![Screenshot from 2024-02-15 14-50-56](https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/16208985/19b734ae-5672-4db8-b78d-46696fd22093)

It doesn't seem possible to scroll in this pane, which would be very useful. Apologies if this is a known issue; I searched the backlog but didn't find

**Comment by timja** [comment]
it's possible on the latest version but that's only available on the weekly / next lts version (21st feb)

**Comment by nre-ableton** [comment]
Thanks, and sorry for the noise :+1:
