### ISSUE TITLE
Differentiate Running Steps in Console View

### ISSUE THREAD

**Issue by stuartrowe** [jenkinsci/pipeline-graph-view-plugin#344]
### What feature do you want to see added?

Running steps are currently styled the same as successful steps in the console view. This is confusing when looking at the logs for an in-progress run.

### Are you interested in contributing this feature?

Yes.

**Comment by stuartrowe** [comment]
I've hacked together a prototype for this. I can put together a PR, but I'll need some input on changes (and design).

**Before**
![image](https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/551572/d121283c-d12d-48b8-99cd-599eb98f5066)
![image](https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/551572/cb40d494-1925-4163-9380-9cc628c23f07)

**After**
![image](https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/551572/7e97ff3b-1739-4ed5-8703-734f15bcf3ed)
![image](https://github.com/jenkinsci/pipeline-graph-view-plugin/assets/551572/89b185f2-95ce-49e2-ba42-327b1b14627e)

**Comment by timja** [comment]
Looks good, links on the right in dark mode will need a different colour
