### ISSUE TITLE
Console View: seems to hang when loading large logs.

### ISSUE THREAD

**Issue by timbrown5** [jenkinsci/pipeline-graph-view-plugin#39]
We have large builds logs (e.g. 17MB) and which take a while to load in Jenkins anyway. The issue is that when we try and load them with the Console View the view itself doesn't offer feedback, so seems to hang.

It would be nice if the front end were able to load the load piece by piece, instead of needing to wait for the backend to finish parsing the log.

**Comment by timja** [comment]
blue ocean does it line by line I think

**Comment by timja** [comment]
My tab just crashes when I try load a 30MB log

![image](https://user-images.githubusercontent.com/21194782/127877737-6c74e97f-d6a8-4b1f-8754-b80e97aef544.png)

Pipeline:

```
pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                    sh '''
                        echo hello world
                    '''
            }
        }
        stage('Build') {
            steps {
                    sh '''
                        echo -e "hello\nworld" > file.txt
                        for i in {1..21}; do cat file.txt file.txt > file2.txt && mv file2.txt file.txt; done
                    '''
                    sh 'du -sh file.txt # 240mb'
                    sh 'cat file.txt'
            }
        }
    }
}
```
