### ISSUE TITLE
Can this be added to the "Status" page instead of a sub-page?

### ISSUE THREAD

**Issue by ykoehler** [jenkinsci/pipeline-graph-view-plugin#4]
I would really like that as soon as I click on a build number, I see this graph instead of looking at blank space

So any change to have an option to have it display there automatically ? 

/job/JobName/1819/

**Comment by dcendents** [comment]
Also maybe display the latest build graph on the job page

**Comment by timja** [comment]
Hi (I wasn't watching this repo oops :( ),

I was thinking of using this is replace that page once there's a bit more content.

Something like this:

![image](https://user-images.githubusercontent.com/21194782/116679848-e82d2180-a9a2-11eb-9acf-8031cba3109b.png)

**Comment by timja** [comment]
This is semi related https://github.com/jenkinsci/pipeline-graph-view-plugin/pull/6

**Comment by timja** [comment]
I had a brief look at this today, I don't think it will fit into the current page,

See an example like https://ci.jenkins.io/job/Core/job/jenkins-test-harness-htmlunit/job/master/24/

I've added a display provider which you can select on your user profile to default notification urls to the graph.

I'll be adding more content to the page soon as well.

**Comment by jonesbusy** [comment]
Hi,

Any update on this feature (Plugin evolved a lot since 2021 😄) ?

I would like to remove the 'pipeline-stage-view' and only use the 'pipeline-graph-view-plugin' but my users are still used to see their pipeline graphics on the job page.

Can this view be included on the job page ? Something like this

![parallel-stages-graph-view](https://user-images.githubusercontent.com/825750/220536678-bf9716f2-e269-4635-9a71-fd1d51b3a4de.png)

Thanks!

**Comment by timja** [comment]
The console view displays the timing information:
https://ci.jenkins.io/job/Plugins/job/kubernetes-plugin/job/PR-1329/9/pipeline-console/

![image](https://user-images.githubusercontent.com/21194782/220578248-64a80ae5-8348-4f59-9451-8bc3868a3099.png)

Seems to have a bit of a limitation in nested stages seem to have the parent timing.
Tests->jdk11
Tests->kind-1
Tests->kind-2
Tests

All have the same timing

> Any update on this feature

There's been progress on adding some cards and more planned, e.g. kind of like this design:
https://jenkins-redesign.vercel.app/project/build/375

You should be able to set the notification url to default to pipeline graph as well (that's in your user settings):

![image](https://user-images.githubusercontent.com/21194782/220579039-51cd68a2-c0ff-4d0f-8090-bc848468e653.png)
