### ISSUE TITLE
Clicking icon on graph should take you to logs

### ISSUE THREAD

**Issue by timja** [jenkinsci/pipeline-graph-view-plugin#40]
### Feature Request
Clicking a stage on graph should take you to the logs page with that stage expanded

**Comment by timbrown5** [comment]
>I'm working on auto-expanding, but having a bit of difficulty, I need to know the parent IDs as well and when I try expand dynamically I get:
>
>>    Material-UI: A component is changing the default expanded state of an uncontrolled TreeView after being initialized. >To suppress this warning opt to use a controlled TreeView.
>
>Part of #40

Added a new branch (`getExpandedNodeHierarchy`) with a function to get the node hierarchy. I have hardcoded the expanded node as I couldn't see how to get the value of `selected-node`.

Also, the way of setting `expanded` seems to set the expanded node permanently, so we should probably find a method that doesn't.

**Comment by timbrown5** [comment]
I would like it if shift-clicking a node opened the console in a new tab, but that doesn't seem to work with me on Firefox.

Not sure if that is out-of-scope.

**Comment by timja** [comment]
> I would like it if shift-clicking a node opened the console in a new tab, but that doesn't seem to work with me on Firefox.
> 
> Not sure if that is out-of-scope.

probably a separate issue, but can be slipped into a fix.

> Added a new branch (getExpandedNodeHierarchy) with a function to get the node hierarchy list of ancestor nodes up to (and including) the one passed by "nodeId". I have hardcoded the expanded node as I couldn't see how to get the value of selected-node.

I tried this for awhile and gave up, defaultExpanded seemed to work ok but you needed to set it statically before the component was initialised, I didn't know the values till component began initialising, but maybe this could be done.

and using `expanded` meant you had to completely take over managing what's expanded

**Comment by timbrown5** [comment]
> and using expanded meant you had to completely take over managing what's expanded

Setting expanded from the state, allowed be to add a `handleToggle` event handler, which allows a set of nodes to be expanded at the start, but users to toggle nodes from there on.
I think, as you say, `defaultExpanded` won't work, as it is set before we set the state.

**Comment by timbrown5** [comment]
Added #42
