### ISSUE TITLE
Label in console output overflows

### ISSUE THREAD

**Issue by timja** [jenkinsci/pipeline-graph-view-plugin#44]
https://ci.jenkins.io/job/Plugins/job/pipeline-graph-view-plugin/job/main/30/pipeline-console/?selected-node=23

![image](https://user-images.githubusercontent.com/21194782/127876106-f15d0ac3-6d17-4da4-9105-3e7bb7981329.png)

**Comment by Jonakss** [comment]
I have the same issue with a curl command
