### ISSUE TITLE
Plugin won't upgrade past version 215.217.v2f6b_05084f10 (no newer versions offered for upgrading)

### ISSUE THREAD

**Issue by jimtut** [jenkinsci/pipeline-graph-view-plugin#507]
### Jenkins and plugins versions report

<details>
  <summary>Environment</summary>

  
  ```text
  Paste the output here
  ```

</details>

### What Operating System are you using (both controller, and any agents involved in the problem)?

Ubuntu 22.04.5 LTS

### Reproduction steps

Plugin version was at 215.217.v2f6b_05084f10.  I hit the downgrade button to go back to 215.vc0ea_557e4d6f, just so I could grab this screenshot.  The latest plug version is NOT being offered, only this older version.  Nothing in the release notes at https://plugins.jenkins.io/pipeline-graph-view/releases/ for the "next" version (216) or any others indicates that our version of Jenkins (2.426.3) is insufficient to run the newer plugin versions.  See image in Actual Results.

### Expected Results

I expect to be offered the latest version to download, like v. 340.

### Actual Results

![image](https://github.com/user-attachments/assets/16c874ec-7265-4054-a211-971e4fdbdf8c)

### Anything else?

It's entirely possible that a newer version of Jenkins is required.  If so, please update the docs or release notes.

**Comment by timja** [comment]
The docs say the minimum version is 2.452.1 for the latest version, see https://plugins.jenkins.io/pipeline-graph-view/
<img width="270" alt="image" src="https://github.com/user-attachments/assets/4802d4e0-a8e6-45ab-8fe2-5c9971652349">
