### ISSUE TITLE
Releases aren't available on GitHub anymore

### ISSUE THREAD

**Issue by gounthar** [jenkinsci/pipeline-graph-view-plugin#531]
### Jenkins and plugins versions report

On https://plugins.jenkins.io/pipeline-graph-view/releases/#version_365.vc5cf79113809 I can see new releases, but on this GitHub repository, I can't see anything new showing up.

I can see some errors in the `cd` action:
```
Error: on='[ERROR] Make sure git status -s is empty before using -Dset.changelist: [package-lock.json] (use -Dignore.dirt to make this nonfatal) -> [Help 1]
Error:  
Error:  To see the full stack trace of the errors, re-run Maven with the -e switch.
Error:  Re-run Maven using the -X switch to enable full debug logging.
Error:  
Error:  For more information about the errors and possible solutions, please read the following articles:
Error:  [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MavenExecutionException'
```

Thanks to @smerle33 for catching this! 🙏

**Comment by timja** [comment]
Weird I had to this another time recently 😢.
Should be fixed by https://github.com/jenkinsci/pipeline-graph-view-plugin/commit/b18bb5c0cfbe1f255f10369463b68808e4bac481

**Comment by timja** [comment]
https://github.com/jenkinsci/pipeline-graph-view-plugin/releases/tag/367.vb_18b_b_5c0cfb_e
