### ISSUE TITLE
Plugin installs "semaphore" step from tests of workflow-support-plugin

### ISSUE THREAD

**Issue by KalleOlaviNiemitalo** [jenkinsci/pipeline-graph-view-plugin#56]
<https://www.jenkins.io/doc/pipeline/steps/pipeline-graph-view/> shows that "Pipeline Graph View Plugin" provides the `semaphore` step ("Test step"). That shouldn't be there. Snippet Generator in Jenkins 2.319.1 likewise displays that step when Pipeline Graph View Plugin 47.v91726240f7a6 is installed. The step seems to be coming from [SemaphoreStep](https://github.com/jenkinsci/workflow-support-plugin/blob/7d4c43699992fa9f2048d1bd4b21cad78b149aa3/src/test/java/org/jenkinsci/plugins/workflow/test/steps/SemaphoreStep.java) in org.jenkins-ci.plugins.workflow-workflow-support-3.8.jar, which is shipped in pipeline-graph-view.jpi even though the classes in it exist only for tests.

**Comment by KalleOlaviNiemitalo** [comment]
I guess it's referenced from here <https://github.com/jenkinsci/pipeline-graph-view-plugin/blob/91726240f7a6c2a23254aaefb817a8c0bfb222ca/pom.xml#L81-L85>

**Comment by timja** [comment]
missing scope test
