### ISSUE TITLE
add step/stage timing on the pipeline graph view

### ISSUE THREAD

**Issue by smerle33** [jenkinsci/pipeline-graph-view-plugin#565]
### What feature do you want to see added?

Hi,

since this [Issue](https://github.com/jenkins-infra/helpdesk/issues/4435)
we are using pipeline graph view as a stage view but we are missing the per stage timing to be able to see what step is taking long.
Is there a way to have this ?

here a snapshot of both view on top of each other, the aim is to have the timing: 

![Image](https://github.com/user-attachments/assets/1134b69d-b832-4f1b-8245-bea6e2be3b6c)

**Comment by timja** [comment]
Only at a per stage level:
https://ci.jenkins.io/job/Core/job/jenkins/job/PR-10043/1/pipeline-console/

![Image](https://github.com/user-attachments/assets/679ecd6a-a630-4fa9-bcaa-f6223ad6d648)

**Comment by timja** [comment]
Duplicate of https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/343
