### ISSUE TITLE
Possibility to download an image of the graph

### ISSUE THREAD

**Issue by Jonakss** [jenkinsci/pipeline-graph-view-plugin#60]
### What feature do you want to see added?

It would be useful for notifications, have the possibility to get a png and/or svg of the graph from the .../pipeline-graph/png
When we make the GET request it returns the image directly.

For example: 
```http://jenkins.url/job/<JobName>/job/<ProjectName>/51/pipeline-graph/png```

**Comment by mikedld** [comment]
Related to #17.

**Comment by timja** [comment]
Duplicate of https://github.com/jenkinsci/pipeline-graph-view-plugin/issues/17
