### ISSUE TITLE
Handle implicit and post stages

### ISSUE THREAD

**Issue by reddwarf69** [jenkinsci/pipeline-graph-view-plugin#85]
### What feature do you want to see added?

Given
```
pipeline {
  agent any

  stages {
    stage('Stage 1') {
      steps {
        echo 'Stage 1'
      }
    }
    stage('Stage 2') {
      steps {
        echo 'Stage 2'
      }
    }
  }

  post {
    always {
      echo 'Done'
    }
  }
}
```

Blue Ocean shows
![Stage 1](https://user-images.githubusercontent.com/1608276/189650532-71c1ef89-95b2-438e-b9be-cf3af62d5ca2.png)
and
![Stage 2](https://user-images.githubusercontent.com/1608276/189650548-245e4505-d332-4d2d-8b1e-713ae097ad2e.png)

While pipeline-graph-view shows
![graph-view](https://user-images.githubusercontent.com/1608276/189650607-87409482-0490-426f-a48c-705a27c5f713.png)
and
![console](https://user-images.githubusercontent.com/1608276/189650632-b3d9d701-e9a3-4cc6-800a-6011fcf3555a.png)

What Blue Ocean does is not ideal, but at least gives you access to the implicit check-out stage and to the post section.

Ideally, I guess pipeline-graph-view would add extra nodes in the graph to represent any implicit stage and the post section.

**Comment by mikedld** [comment]
Simply returning `false` from `PipelineNodeUtil.isSyntheticStage()` makes the stages show up in both graph and log views. Do we want to show them like this but render in a way that hints to the user that they're synthetic (different color/contour, font style)? Not sure why BlueOcean decided to hide them (jenkinsci/blueocean-plugin#608 and linked [JENKINS-38150](https://issues.jenkins.io/browse/JENKINS-38150) don't give any reasoning behind it); TBH I never liked that approach of prepending/appending the steps of those synthetic stages to my own stages... Thougts?

**Comment by reddwarf69** [comment]
I don't really mind. Specially with the "post" part which, I don't know the internal details, but in my mind it's just another "stage" and I would not have a problem with it showing the same as the rest in the graph view.
I guess there is more of an argument to make the implicit checkout show somehow differently, but I use the skipDefaultCheckout option anyway.

**Comment by timja** [comment]
> Not sure why BlueOcean decided to hide them

Not sure the issues don't seem to say why, one issue though is these labels are awfully long which make it look terrible.

But yeah not hiding synthetic stages seems to work quite well. It makes sense for checkout to be it's own stage and not randomly put in another one...

<img width="696" alt="image" src="https://user-images.githubusercontent.com/21194782/189835554-c65ebaeb-cb4f-400e-a2bc-52deba350658.png">
